# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20181212_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 7, 5, 2, 554491, tzinfo=utc)),
        ),
    ]
